### ISSUE TITLE
Unable to download this.

### ISSUE THREAD

**Issue by jcperil** [Foxite/YoutubeDL#11]
YouTube link: https://youtu.be/mRhL0PLwrrI
When I try to download the above using YouTubeDL, I get an error message (see Attachment).
![ytdl](https://user-images.githubusercontent.com/89805719/163478446-e4e4dfcb-6d11-4bd2-9388-76277569f984.jpg)

Device: Redmi Note 10 Pro, MIUI 13.0.1
Android version: 12

**Comment by Foxite** [comment]
Unfortunately I can't maintain this app anymore.
