### ISSUE TITLE
add an apk example in README.md 

### ISSUE THREAD

**Issue by xibr** [Foxite/YoutubeDL#2]
hi, can you build apk and share it or add an url to README.md file.

**Comment by Foxite** [comment]
Hi, I have added a [release with an apk](https://github.com/Foxite/YoutubeDL/releases/tag/0.1). The app should work, but YoutubeExplode might not work properly.

**Comment by xibr** [comment]
I installed it and the app is working but can't download anything same you said  YoutubeExplode not work.

**Comment by Foxite** [comment]
You might be experiencing #3.

It appears the only way you can get it to work, right now, is to install Visual Studio and the Xamarin package, and install a debug-mode build via adb. This is quite involved, I wouldn't recommend doing it unless you already have the necessary tools installed.

By the way, if you have any idea why this is happening, please let me know.

**Comment by Foxite** [comment]
@bunaif [This release](https://github.com/Foxite/YoutubeDL/releases/tag/0.1.1) should fix the problem.

**Comment by xibr** [comment]
Hi, now is working. But without notification.

Check this.
https://stackoverflow.com/questions/43093260/notification-not-showing-in-oreo

I'm using android 10.

**Comment by Foxite** [comment]
That would explain why notifications aren't working in the emulator, which runs android 9 (as opposed to my phone, which runs 7).

Thanks for testing, I'll get back on the notifications.
