### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [Foxite/YoutubeDL#6]
You can add Screenshots for F-Droid, too, if you want. https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/ https://gitlab.com/snippets/1895688 That was simply information about what is still possible. You would then only have to enter the screenshots in fastlane.

**Comment by Foxite** [comment]
I've added two screenshots. Since this app doesn't really have its own UI, I hope these will do.

**Comment by mondlicht-und-sterne** [comment]
OK, then you can also close the issue.
